---
title: "R-programing"
author: "ZeesZerro"
date: "20 กรกฎาคม 2560"
output: html_document
---

Install package
```{r}
install.packages(c("MASS", "httr", "XML", "xml2", "ggplot2", "ggplot2movies", "plyr", "curl", "rvest", "data.table"))
```

load library
```{r}
library(MASS)
```

show data
```{r}
View(birthwt)
View(Cars93)
```

change colname
```{r}
colnames(birthwt) <- c("birthwt.below.2500", "mother.age", "mother.weight", 
    "race", "mother.smokes", "previous.prem.labor", "hypertension", "uterine.irr", 
    "physician.visits", "birthwt.grams")
```

load library
```{r}
library(plyr)
```


change value to text
```{r}
birthwt <- transform(birthwt, 
            race = as.factor(mapvalues(race, c(1, 2, 3), 
                              c("white","black", "other"))),
            mother.smokes = as.factor(mapvalues(mother.smokes, c(0,1), c("no", "yes"))),
            hypertension = as.factor(mapvalues(hypertension, 
                              c(0,1), c("no", "yes"))),
            uterine.irr = as.factor(mapvalues(uterine.irr, 
                              c(0,1), c("no", "yes")))
            )
```

change value in visit, if visit >= 3 then visit<-"3.or.more" and add new col phy.visit.binned to birthwt
```{r}
phys.visit.binned <- birthwt$physician.visits
phys.visit.binned[phys.visit.binned >= 3] <- "3.or.more"
birthwt <- transform(birthwt, phys.visit.binned = as.factor(phys.visit.binned))

birthwt$phys.visit.binned
```

